### ISSUE TITLE
Bbox issue for some countries

### ISSUE THREAD

**Issue by barshathakuri** [IFRCGo/alert-hub-backend#50]
> Looks good but i think there some issues. when i click on New Zealand it goes to South Africa. also when i click on countries like Brazil, India and Russia, it does not nicely pan into the country as it does for Nigeria, Germany or Poland.

Issue detail and fix: https://github.com/IFRCGo/alert-hub-backend/issues/50#issuecomment-2133681327

**Comment by barshathakuri** [comment]
@nnjemie Replying to the question
For Russia and New Zealand, it is an issue with bbox calculation using geoarea from IFRC. Because of anti-mederian, we may have issue with countries which touches it.

For now, we have added custom bbox for Russia. We will also add custom bbox for those countries

cc: @thenav56

**Comment by nnjemie** [comment]
could you please still review the various b-boxes? We still need to manually adjust the b-box data for countries that have over seas territories so that it goes to the main land, for example France and possibly the Netherlands. it seems to be fine for the UK. 
cc @barshathakuri

**Comment by barshathakuri** [comment]
Sure @nnjemie

**Comment by thenav56** [comment]
### Update

We currently have an issue with bounding boxes (bbox) due to:
1. The Antimeridian
2. Colonial Boundaries

To address this, we have created custom bboxes for countries and admin1 regions. This approach avoids the complex logic needed to calculate the correct bboxes directly from polygons. If the source database (i.e., IFRC) resolves this issue in the future, we can switch to their data.

## Country Bboxes

Below are the country bboxes generated from GeoJSON provided by IFRC:
![Country Bboxes from IFRC](https://github.com/IFRCGo/alert-hub-backend/assets/7059255/67072c01-856f-4cf6-b4e2-ce2f9c83421b)

**Note:** GeoJSON used for the image: [country-bbox.json](https://github.com/IFRCGo/alert-hub-backend/files/15457378/country-bbox.json)

Here are the manually fixed country bboxes:
![Fixed Country Bboxes](https://github.com/IFRCGo/alert-hub-backend/assets/7059255/be8555d8-adc9-4be2-8c88-89378b9534a5)

**Note:** GeoJSON used for the image: [country-bbox-fixed.json](https://github.com/IFRCGo/alert-hub-backend/files/15457379/country-bbox-fixed.json), generated from [this file](https://github.com/IFRCGo/alert-hub-backend/blob/develop/apps/cap_feed/data_injector/country-bbox.json).

## Admin1 Bboxes

Below are the admin1 bboxes generated from GeoJSON provided by IFRC:
![Admin1 Bboxes from IFRC](https://github.com/IFRCGo/alert-hub-backend/assets/7059255/efa3b322-999a-412b-90e0-e3311951678a)

**Note:** GeoJSON used for the image: [admin1-bbox.json](https://github.com/IFRCGo/alert-hub-backend/files/15457414/admin1-bbox.json)

Here are the manually fixed admin1 bboxes:
![Fixed Admin1 Bboxes](https://github.com/IFRCGo/alert-hub-backend/assets/7059255/c7ca01e5-10d0-45ac-a4d2-a304d0aab858)

**Note:** GeoJSON used for the image: [admin1-bbox-fixed.json](https://github.com/IFRCGo/alert-hub-backend/files/15457432/admin1-bbox-fixed.json), generated from [this file](https://github.com/IFRCGo/alert-hub-backend/blob/develop/apps/cap_feed/data_injector/admin1-bbox.json).

**Comment by thenav56** [comment]
Update: This has been pushed to production. If any more changes are required related to custom bbox, let's reopen this ticket.
